# PSRule configuration for Azure infrastructure validation
# Addresses AZR-000279 false positive with AVM SQL Server module v0.15.0

# Global configuration
configuration:
  AZURE_BICEP_FILE_EXPANSION: true
  AZURE_PARAMETER_FILE_EXPANSION: true

# Completely exclude the problematic rule
rule:
  exclude:
    - 'Azure.Deployment.OutputSecretValue'

# Additional suppressions by deployment name
suppression:
  Azure.Deployment.OutputSecretValue:
    - 'sqltestb5992-sqlserver-deployment'
    - '*-sqlserver-deployment'
    - '*sqlserver*'
  AZR-000279:
    - 'sqltestb5992-sqlserver-deployment'
    - '*-sqlserver-deployment'  
    - '*sqlserver*'