# PSRule configuration for Azure infrastructure validation
# https://azure.github.io/PSRule.Rules.Azure/

configuration:
  # Suppress specific rules for known issues
  suppression:
    AZR-000279:
      # Suppress Azure.Deployment.OutputSecretValue for SQL Server deployments
      # This is required due to a known issue with AVM SQL Server module v0.15.0
      # where the module outputs location information that PSRule flags as sensitive
      - 'sqltestb5992-sqlserver-deployment'
      - '*-sqlserver-deployment'
      - '*-sql-server*'
      - 'sqlServer'
      - '*.res.sql-server.*'
      # Pattern for the specific deployment from the error message
      - '46d3xbcp.res.sql-server.0-15-0.7d16'