name: AZD Template Validation
on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  template_validation:
    runs-on: ubuntu-latest
    name: azd template validation
    steps:
      - uses: actions/checkout@v4

      - name: Run preprovision
        run: bash ./scripts/preprovision-integrated.sh
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}

      - uses: microsoft/template-validation-action@Latest
        with:
          validateAzd: ${{ vars.TEMPLATE_VALIDATE_AZD }}
          useDevContainer: ${{ vars.TEMPLATE_USE_DEV_CONTAINER }}
        id: validation
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          fabricCapacityMode: 'none'
      - name: print result
        run: cat ${{ steps.validation.outputs.resultFile }}
